version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
    environment:
      SECRET_KEY: "ваш_очень_длинный_и_случайный_секретный_ключ_для_фласка"
      FLASK_ENV: production
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      # - "443:443" # for HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # НОВОЕ: Монтируем robots.txt в стандартное место Nginx для статики
      - ./robots.txt:/usr/share/nginx/html/robots.txt:ro
    depends_on:
      - web
    restart: always