
services:
  web:
    build: .
    ports:
      - "80:5000"
    volumes:
      - .:/app
    environment:
      SECRET_KEY: "ваш_очень_длинный_и_случайный_секретный_ключ_для_фласка"
      FLASK_ENV: production
    restart: always